import { MigrationInterface, QueryRunner } from "typeorm";

export class Envelope1761278350843 implements MigrationInterface {
    name = 'Envelope1761278350843'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "username" varchar(50) NOT NULL, "email" varchar(100) NOT NULL, "password" varchar(255) NOT NULL, "role" varchar CHECK( "role" IN ('USER','ADMIN') ) NOT NULL DEFAULT ('USER'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "created_at", "updated_at", "username", "email", "password", "role") SELECT "id", "created_at", "updated_at", "username", "email", "password", "role" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "envelope" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "name" varchar(100) NOT NULL, "description" text, "envelpe_amount" decimal(10,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT (1), "user_id" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "temporary_transactions" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "amount" decimal(10,2) NOT NULL, "currency" varchar(50) NOT NULL, "description" varchar(255), "user_id" varchar NOT NULL, "category_id" varchar NOT NULL, "envelope_id" varchar, CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT, CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT)`);
        await queryRunner.query(`INSERT INTO "temporary_transactions"("id", "created_at", "updated_at", "amount", "currency", "description", "user_id", "category_id") SELECT "id", "created_at", "updated_at", "amount", "currency", "description", "user_id", "category_id" FROM "transactions"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`ALTER TABLE "temporary_transactions" RENAME TO "transactions"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "username" varchar(50) NOT NULL, "email" varchar(100) NOT NULL, "password" varchar(255) NOT NULL, "role" varchar CHECK( "role" IN ('USER','ADMIN') ) NOT NULL DEFAULT ('USER'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "created_at", "updated_at", "username", "email", "password", "role") SELECT "id", "created_at", "updated_at", "username", "email", "password", "role" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "temporary_envelope" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "name" varchar(100) NOT NULL, "description" text, "envelpe_amount" decimal(10,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT (1), "user_id" varchar NOT NULL, CONSTRAINT "FK_b42c9a53d41252d7187bf321257" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_envelope"("id", "created_at", "updated_at", "name", "description", "envelpe_amount", "is_active", "user_id") SELECT "id", "created_at", "updated_at", "name", "description", "envelpe_amount", "is_active", "user_id" FROM "envelope"`);
        await queryRunner.query(`DROP TABLE "envelope"`);
        await queryRunner.query(`ALTER TABLE "temporary_envelope" RENAME TO "envelope"`);
        await queryRunner.query(`CREATE TABLE "temporary_transactions" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "amount" decimal(10,2) NOT NULL, "currency" varchar(50) NOT NULL, "description" varchar(255), "user_id" varchar NOT NULL, "category_id" varchar NOT NULL, "envelope_id" varchar, CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT, CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT, CONSTRAINT "FK_1238cbb5fa225575e81ce739895" FOREIGN KEY ("envelope_id") REFERENCES "envelope" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT)`);
        await queryRunner.query(`INSERT INTO "temporary_transactions"("id", "created_at", "updated_at", "amount", "currency", "description", "user_id", "category_id", "envelope_id") SELECT "id", "created_at", "updated_at", "amount", "currency", "description", "user_id", "category_id", "envelope_id" FROM "transactions"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`ALTER TABLE "temporary_transactions" RENAME TO "transactions"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transactions" RENAME TO "temporary_transactions"`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "amount" decimal(10,2) NOT NULL, "currency" varchar(50) NOT NULL, "description" varchar(255), "user_id" varchar NOT NULL, "category_id" varchar NOT NULL, "envelope_id" varchar, CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT, CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT)`);
        await queryRunner.query(`INSERT INTO "transactions"("id", "created_at", "updated_at", "amount", "currency", "description", "user_id", "category_id", "envelope_id") SELECT "id", "created_at", "updated_at", "amount", "currency", "description", "user_id", "category_id", "envelope_id" FROM "temporary_transactions"`);
        await queryRunner.query(`DROP TABLE "temporary_transactions"`);
        await queryRunner.query(`ALTER TABLE "envelope" RENAME TO "temporary_envelope"`);
        await queryRunner.query(`CREATE TABLE "envelope" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "name" varchar(100) NOT NULL, "description" text, "envelpe_amount" decimal(10,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT (1), "user_id" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "envelope"("id", "created_at", "updated_at", "name", "description", "envelpe_amount", "is_active", "user_id") SELECT "id", "created_at", "updated_at", "name", "description", "envelpe_amount", "is_active", "user_id" FROM "temporary_envelope"`);
        await queryRunner.query(`DROP TABLE "temporary_envelope"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "username" varchar(50) NOT NULL, "email" varchar(100) NOT NULL, "password" varchar(255) NOT NULL, "role" varchar CHECK( "role" IN ('USER','ADMIN') ) NOT NULL DEFAULT ('USER'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "created_at", "updated_at", "username", "email", "password", "role") SELECT "id", "created_at", "updated_at", "username", "email", "password", "role" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`ALTER TABLE "transactions" RENAME TO "temporary_transactions"`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "amount" decimal(10,2) NOT NULL, "currency" varchar(50) NOT NULL, "description" varchar(255), "user_id" varchar NOT NULL, "category_id" varchar NOT NULL, CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT, CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT)`);
        await queryRunner.query(`INSERT INTO "transactions"("id", "created_at", "updated_at", "amount", "currency", "description", "user_id", "category_id") SELECT "id", "created_at", "updated_at", "amount", "currency", "description", "user_id", "category_id" FROM "temporary_transactions"`);
        await queryRunner.query(`DROP TABLE "temporary_transactions"`);
        await queryRunner.query(`DROP TABLE "envelope"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "username" varchar(50) NOT NULL, "email" varchar(100) NOT NULL, "password" varchar(255) NOT NULL, "role" varchar CHECK( "role" IN ('USER','ADMIN') ) NOT NULL DEFAULT ('USER'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "created_at", "updated_at", "username", "email", "password", "role") SELECT "id", "created_at", "updated_at", "username", "email", "password", "role" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
    }

}
